name: Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    services:
      neo4j:
        image: neo4j
        env:
          NEO4J_AUTH: neo4j/test
        ports:
          - 7474:7474
          - 7687:7687
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v2
        with:
          url: http://neo4j:7474/browser
          follow-redirect: false
          max-attempts: 5
          retry-delay: 5s
          retry-all: false
      - name: Check out repository code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: npm install
      - name: Run Tests
        run: npm run test
        env:
          NEO4J_HTTP_URL: http://localhost:7474
          NEO4J_BOLT_URL: bolt://localhost:7687
          NEO4J_USER: neo4j
          NEO4J_PASSWORD: test
          NEO4J_DB: db
